import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Sparkles, Printer, Save, CheckCircle2, Eye, Layout } from 'lucide-react';

export const PaperGeneratorView: React.FC = () => {
  const { questionBank, classes, settings, addQuestionPaper } = useApp();

  const [activeTab, setActiveTab] = useState<'setup' | 'preview'>('setup');
  const [selectedClassId, setSelectedClassId] = useState<string>(classes[0]?.id || '');
  const [subject, setSubject] = useState<string>('Mathematics');
  const [examName, setExamName] = useState<string>('Mid Term Examination 2026-27');
  const [timeAllowed, setTimeAllowed] = useState<string>('2 Hours');
  const [template, setTemplate] = useState<'Classic' | 'Modern' | 'CBSE Style' | 'Minimal'>('CBSE Style');

  const [includeMCQ, setIncludeMCQ] = useState(true);
  const [mcqCount, setMcqCount] = useState(5);
  const [includeShort, setIncludeShort] = useState(true);
  const [shortCount, setShortCount] = useState(3);
  const [includeLong, setIncludeLong] = useState(true);
  const [longCount, setLongCount] = useState(2);

  // Generated Paper Data
  const [generatedPaper, setGeneratedPaper] = useState<any | null>(null);

  const handleGenerate = () => {
    const classObj = classes.find(c => c.id === selectedClassId);
    const className = classObj ? classObj.name : 'Class 6A';

    const availableForSubject = questionBank.filter(
      q => q.classId === selectedClassId || q.subject.toLowerCase() === subject.toLowerCase()
    );

    let selectedQuestions: any[] = [];

    // Filter MCQs
    if (includeMCQ) {
      const mcqs = availableForSubject.filter(q => q.type === 'MCQ');
      selectedQuestions.push(...mcqs.slice(0, mcqCount));
    }
    // Filter Short
    if (includeShort) {
      const shorts = availableForSubject.filter(q => q.type === 'Short Answer');
      selectedQuestions.push(...shorts.slice(0, shortCount));
    }
    // Filter Long
    if (includeLong) {
      const longs = availableForSubject.filter(q => q.type === 'Long Answer');
      selectedQuestions.push(...longs.slice(0, longCount));
    }

    // If empty fallback dummy questions
    if (selectedQuestions.length === 0) {
      selectedQuestions = [
        {
          questionText: 'What is the sum of angles in a triangle?',
          type: 'MCQ',
          marks: 1,
          mcqOptions: ['180°', '90°', '360°', '270°']
        },
        {
          questionText: 'State and prove Pythagoras theorem with diagram.',
          type: 'Long Answer',
          marks: 5
        }
      ];
    }

    const totalMarks = selectedQuestions.reduce((sum, q) => sum + (q.marks || 1), 0);

    const paperObj = {
      schoolName: settings.name,
      logoUrl: settings.logoUrl,
      examName,
      className,
      subject,
      time: timeAllowed,
      maxMarks: totalMarks,
      template,
      questions: selectedQuestions
    };

    setGeneratedPaper(paperObj);
    setActiveTab('preview');
  };

  const handleSaveToQPapers = () => {
    if (!generatedPaper) return;
    addQuestionPaper({
      classId: selectedClassId,
      subject,
      examType: examName,
      title: `${subject} - ${examName} (${template} Template)`,
      isAutoGenerated: true,
      generatedContent: generatedPaper
    });
    alert('💾 Generated Paper Saved to Question Papers Library!');
  };

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 bg-[#16122d] border border-purple-900/30 rounded-2xl shadow-xl">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-amber-400" /> Automated Exam Paper Generator
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Auto-generate professional formatted exam papers from Question Bank with custom templates
          </p>
        </div>

        <div className="flex items-center gap-1 p-1 bg-[#100d24] border border-purple-900/40 rounded-xl">
          <button
            onClick={() => setActiveTab('setup')}
            className={`px-3.5 py-1.5 text-xs font-semibold rounded-lg transition-all ${
              activeTab === 'setup' ? 'bg-purple-600 text-white' : 'text-slate-400 hover:text-white'
            }`}
          >
            ⚙️ Setup
          </button>
          <button
            onClick={() => setActiveTab('preview')}
            disabled={!generatedPaper}
            className={`px-3.5 py-1.5 text-xs font-semibold rounded-lg transition-all ${
              activeTab === 'preview' ? 'bg-purple-600 text-white' : 'text-slate-500'
            }`}
          >
            👁️ Preview
          </button>
        </div>
      </div>

      {activeTab === 'setup' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Setup Form */}
          <div className="p-5 bg-[#16122d] border border-purple-900/30 rounded-2xl space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              ⚡ Quick Generate Configuration
            </h3>

            <div className="space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Target Class *</label>
                  <select
                    value={selectedClassId}
                    onChange={(e) => setSelectedClassId(e.target.value)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                  >
                    {classes.map(c => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Subject Name *</label>
                  <input
                    type="text"
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white font-semibold"
                  />
                </div>
              </div>

              <div>
                <label className="block text-slate-300 font-semibold mb-1">Exam Header Title *</label>
                <input
                  type="text"
                  value={examName}
                  onChange={(e) => setExamName(e.target.value)}
                  className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Time Allowed</label>
                  <input
                    type="text"
                    value={timeAllowed}
                    onChange={(e) => setTimeAllowed(e.target.value)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                  />
                </div>
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Layout Template Style</label>
                  <select
                    value={template}
                    onChange={(e) => setTemplate(e.target.value as any)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white font-semibold text-purple-300"
                  >
                    <option value="CBSE Style">CBSE Double Border Style</option>
                    <option value="Classic">Classic Black & White</option>
                    <option value="Modern">Modern Header Gradient</option>
                    <option value="Minimal">Ultra Minimalist</option>
                  </select>
                </div>
              </div>

              {/* Question Types Selector */}
              <div className="p-3 bg-[#100d24] rounded-xl border border-purple-900/30 space-y-2">
                <div className="text-xs font-bold text-purple-300">Question Types & Quantity:</div>

                <div className="flex items-center justify-between">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeMCQ}
                      onChange={(e) => setIncludeMCQ(e.target.checked)}
                      className="w-4 h-4 rounded text-purple-600"
                    />
                    <span className="text-slate-200">MCQs (1 Mark each)</span>
                  </label>
                  <input
                    type="number"
                    min={1}
                    value={mcqCount}
                    onChange={(e) => setMcqCount(Number(e.target.value))}
                    className="w-16 bg-[#16122e] border border-purple-900/40 text-center rounded-lg py-1 font-mono text-white"
                  />
                </div>

                <div className="flex items-center justify-between">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeShort}
                      onChange={(e) => setIncludeShort(e.target.checked)}
                      className="w-4 h-4 rounded text-purple-600"
                    />
                    <span className="text-slate-200">Short Answer Questions</span>
                  </label>
                  <input
                    type="number"
                    min={1}
                    value={shortCount}
                    onChange={(e) => setShortCount(Number(e.target.value))}
                    className="w-16 bg-[#16122e] border border-purple-900/40 text-center rounded-lg py-1 font-mono text-white"
                  />
                </div>

                <div className="flex items-center justify-between">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeLong}
                      onChange={(e) => setIncludeLong(e.target.checked)}
                      className="w-4 h-4 rounded text-purple-600"
                    />
                    <span className="text-slate-200">Long Answer Questions</span>
                  </label>
                  <input
                    type="number"
                    min={1}
                    value={longCount}
                    onChange={(e) => setLongCount(Number(e.target.value))}
                    className="w-16 bg-[#16122e] border border-purple-900/40 text-center rounded-lg py-1 font-mono text-white"
                  />
                </div>
              </div>

              <button
                onClick={handleGenerate}
                className="w-full py-3 bg-gradient-to-r from-purple-600 via-indigo-600 to-amber-600 hover:brightness-110 text-white font-extrabold text-xs rounded-xl shadow-xl flex items-center justify-center gap-2 transition-all"
              >
                <Sparkles className="w-4 h-4 text-amber-300" /> ⚡ Generate Question Paper Now
              </button>
            </div>
          </div>

          {/* Template Info Card */}
          <div className="p-5 bg-[#16122d] border border-purple-900/30 rounded-2xl space-y-4 flex flex-col justify-between">
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <Layout className="w-4 h-4 text-purple-400" /> Template Style Preview
              </h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Selected Template: <strong className="text-purple-300">{template}</strong>
              </p>
              <div className="p-4 bg-white text-slate-900 rounded-xl border border-slate-300 text-[10px] space-y-2 shadow-inner">
                <div className="text-center font-bold uppercase border-b pb-1">{settings.name}</div>
                <div className="text-center font-semibold">{examName}</div>
                <div className="flex justify-between border-t pt-1 font-mono">
                  <span>Class: 6A</span>
                  <span>Time: {timeAllowed}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* Preview Tab */
        <div className="space-y-4">
          <div className="flex items-center justify-between p-4 bg-[#16122d] border border-purple-900/30 rounded-2xl">
            <div className="text-xs text-slate-300">
              Generated Paper Ready · Template: <strong>{generatedPaper.template}</strong>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleSaveToQPapers}
                className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs rounded-xl flex items-center gap-1.5 shadow-md"
              >
                <Save className="w-4 h-4" /> 💾 Save to Q-Papers
              </button>
              <button
                onClick={() => window.print()}
                className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs rounded-xl flex items-center gap-1.5 shadow-md"
              >
                <Printer className="w-4 h-4" /> 🖨️ Print Paper
              </button>
            </div>
          </div>

          {/* Formatted Paper Sheet */}
          <div className="bg-white text-slate-900 rounded-2xl p-8 shadow-2xl space-y-6 max-w-3xl mx-auto border border-slate-200">
            {/* Header */}
            <div className="text-center border-b-2 border-slate-900 pb-4 space-y-1">
              {generatedPaper.logoUrl && (
                <img src={generatedPaper.logoUrl} alt="School Logo" className="w-12 h-12 mx-auto rounded-full object-cover mb-1" />
              )}
              <h1 className="text-2xl font-extrabold uppercase tracking-tight">{generatedPaper.schoolName}</h1>
              <div className="text-xs font-bold text-slate-700">{generatedPaper.examName}</div>
              <div className="flex items-center justify-between text-xs text-slate-800 pt-3 font-mono font-bold border-t border-slate-300 mt-2">
                <span>Subject: {generatedPaper.subject}</span>
                <span>Class: {generatedPaper.className}</span>
                <span>Time: {generatedPaper.time}</span>
                <span>Max Marks: {generatedPaper.maxMarks}</span>
              </div>
            </div>

            {/* Questions */}
            <div className="space-y-5 text-xs">
              {generatedPaper.questions.map((q: any, idx: number) => (
                <div key={idx} className="space-y-1">
                  <div className="font-bold flex items-start justify-between text-sm">
                    <span>Q{idx + 1}. {q.questionText}</span>
                    <span className="font-mono text-slate-600 font-bold">[{q.marks} Marks]</span>
                  </div>
                  {q.mcqOptions && (
                    <div className="grid grid-cols-2 gap-2 pl-4 pt-1 font-mono text-xs text-slate-800">
                      {q.mcqOptions.map((opt: string, oIdx: number) => (
                        <div key={oIdx}>({String.fromCharCode(65 + oIdx)}) {opt}</div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
