import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { FileCode, Upload, Download, Eye, Trash2, X, Printer, Sparkles } from 'lucide-react';

export const QuestionPapersView: React.FC = () => {
  const { questionPapers, addQuestionPaper, deleteQuestionPaper, classes, role } = useApp();
  const [selectedClassId, setSelectedClassId] = useState<string>('all');
  const [showModal, setShowModal] = useState(false);
  const [previewPaper, setPreviewPaper] = useState<any | null>(null);

  const [classId, setClassId] = useState(classes[0]?.id || '');
  const [subject, setSubject] = useState('');
  const [examType, setExamType] = useState('Mid Term');
  const [title, setTitle] = useState('');

  const handleSave = () => {
    if (!title.trim() || !subject.trim()) return;
    addQuestionPaper({
      classId,
      subject,
      examType,
      title,
      isAutoGenerated: false
    });
    setShowModal(false);
    setTitle('');
    setSubject('');
  };

  const filteredPapers = questionPapers.filter(q => selectedClassId === 'all' || q.classId === selectedClassId);

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 bg-[#16122d] border border-purple-900/30 rounded-2xl shadow-xl">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <FileCode className="w-5 h-5 text-purple-400" /> Question Papers Library
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Access exam question papers (both uploaded and auto-generated via Paper Generator)
          </p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={selectedClassId}
            onChange={(e) => setSelectedClassId(e.target.value)}
            className="bg-[#100d24] border border-purple-900/40 text-slate-200 text-xs rounded-xl px-3 py-2.5"
          >
            <option value="all">All Classes ({questionPapers.length})</option>
            {classes.map(c => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>

          {(role === 'admin' || role === 'teacher') && (
            <button
              onClick={() => setShowModal(true)}
              className="px-4 py-2.5 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-bold text-xs rounded-xl flex items-center gap-2 shadow-lg shrink-0"
            >
              <Upload className="w-4 h-4" /> 📤 Upload Paper
            </button>
          )}
        </div>
      </div>

      {/* Question Papers List */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredPapers.map(qp => {
          const cls = classes.find(c => c.id === qp.classId);

          return (
            <div
              key={qp.id}
              className="p-5 bg-[#16122d] border border-purple-900/30 rounded-2xl hover:border-purple-500/50 transition-all space-y-3 flex flex-col justify-between"
            >
              <div className="space-y-2">
                <div className="flex items-start justify-between">
                  <span className={`px-2 py-0.5 rounded font-bold text-[10px] uppercase border ${
                    qp.isAutoGenerated
                      ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                      : 'bg-purple-900/40 text-purple-300 border-purple-700/40'
                  }`}>
                    {qp.isAutoGenerated ? '⚡ Auto-Generated' : '📤 Uploaded File'}
                  </span>

                  {(role === 'admin' || role === 'teacher') && (
                    <button
                      onClick={() => deleteQuestionPaper(qp.id)}
                      className="p-1.5 text-slate-400 hover:text-rose-400 hover:bg-rose-900/30 rounded-lg"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>

                <div>
                  <div className="text-xs font-semibold text-purple-300">{cls ? cls.name : 'Class'} · {qp.subject} ({qp.examType})</div>
                  <h3 className="font-bold text-white text-sm mt-0.5">{qp.title}</h3>
                </div>
              </div>

              <div className="pt-2 border-t border-purple-900/20 space-y-2 text-xs">
                <div className="text-[10px] text-slate-400">Date: {qp.uploadDate}</div>

                {qp.generatedContent ? (
                  <button
                    onClick={() => setPreviewPaper(qp.generatedContent)}
                    className="w-full py-2 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-bold rounded-xl flex items-center justify-center gap-1.5 transition-all text-xs shadow-md"
                  >
                    <Eye className="w-3.5 h-3.5" /> View / Print Paper
                  </button>
                ) : (
                  <button
                    onClick={() => alert(`⬇ Downloading Question Paper: ${qp.title}`)}
                    className="w-full py-2 bg-[#100d24] hover:bg-purple-900/30 border border-purple-900/40 text-purple-300 font-semibold rounded-xl flex items-center justify-center gap-1.5 transition-all text-xs"
                  >
                    <Download className="w-3.5 h-3.5" /> Download Paper (PDF)
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Upload Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
          <div className="w-full max-w-md bg-[#16122e] border border-purple-800/40 rounded-2xl p-6 shadow-2xl relative text-slate-100 space-y-4">
            <button onClick={() => setShowModal(false)} className="absolute right-4 top-4 p-1.5 text-slate-400 hover:text-white rounded-lg">
              <X className="w-5 h-5" />
            </button>

            <h3 className="text-base font-bold text-white">Upload Question Paper</h3>

            <div className="space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Target Class *</label>
                  <select
                    value={classId}
                    onChange={(e) => setClassId(e.target.value)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                  >
                    {classes.map(c => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-slate-300 font-semibold mb-1">Exam Type</label>
                  <select
                    value={examType}
                    onChange={(e) => setExamType(e.target.value)}
                    className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                  >
                    <option value="Mid Term">Mid Term</option>
                    <option value="Unit Test 1">Unit Test 1</option>
                    <option value="Final Exam">Final Exam</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-slate-300 font-semibold mb-1">Subject Name *</label>
                <input
                  type="text"
                  placeholder="e.g. Mathematics"
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                />
              </div>

              <div>
                <label className="block text-slate-300 font-semibold mb-1">Paper Title *</label>
                <input
                  type="text"
                  placeholder="e.g. Class 6A Mathematics Mid-Term Exam Paper"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full bg-[#100d24] border border-purple-900/40 rounded-xl px-3 py-2 text-white"
                />
              </div>

              <div className="p-4 border border-dashed border-purple-800 rounded-xl text-center bg-[#100d24] cursor-pointer hover:border-purple-500">
                <Upload className="w-6 h-6 text-purple-400 mx-auto mb-1" />
                <span className="text-xs text-slate-300 font-semibold">Choose Question Paper File (PDF)</span>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-purple-900/30">
              <button onClick={() => setShowModal(false)} className="px-4 py-2 text-xs bg-[#221c47] text-slate-300 rounded-xl">
                Cancel
              </button>
              <button
                onClick={handleSave}
                className="px-4 py-2 text-xs font-bold bg-purple-600 hover:bg-purple-500 text-white rounded-xl shadow-md"
              >
                Save Paper
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Generated Paper Preview Modal */}
      {previewPaper && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 overflow-y-auto">
          <div className="w-full max-w-2xl bg-white text-slate-900 rounded-2xl p-8 shadow-2xl relative space-y-6 my-8 print:p-0 print:shadow-none">
            <button onClick={() => setPreviewPaper(null)} className="absolute right-4 top-4 p-2 text-slate-400 hover:text-black rounded-lg print:hidden">
              <X className="w-6 h-6" />
            </button>

            {/* Paper Header */}
            <div className="text-center border-b pb-4 space-y-1">
              <h1 className="text-xl font-extrabold uppercase tracking-tight text-slate-900">{previewPaper.schoolName}</h1>
              <div className="text-xs text-slate-600 font-semibold">{previewPaper.examName} · Class {previewPaper.className}</div>
              <div className="flex items-center justify-between text-xs text-slate-700 pt-2 font-mono border-t border-slate-200">
                <span>Subject: <strong>{previewPaper.subject}</strong></span>
                <span>Time: {previewPaper.time}</span>
                <span>Max Marks: {previewPaper.maxMarks}</span>
              </div>
            </div>

            {/* Questions List */}
            <div className="space-y-4 text-xs">
              {previewPaper.questions.map((q: any, idx: number) => (
                <div key={idx} className="space-y-1">
                  <div className="font-bold flex items-start justify-between">
                    <span>Q{idx + 1}. {q.questionText}</span>
                    <span className="font-mono text-slate-500">[{q.marks} Marks]</span>
                  </div>
                  {q.mcqOptions && (
                    <div className="grid grid-cols-2 gap-2 pl-4 pt-1 font-mono text-[11px] text-slate-700">
                      {q.mcqOptions.map((opt: string, oIdx: number) => (
                        <div key={oIdx}>({String.fromCharCode(65 + oIdx)}) {opt}</div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="pt-4 border-t flex justify-end gap-2 print:hidden">
              <button
                onClick={() => window.print()}
                className="px-5 py-2.5 bg-slate-900 text-white font-bold text-xs rounded-xl flex items-center gap-2 shadow-lg"
              >
                <Printer className="w-4 h-4" /> Print / Save as PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
