export type Role = 'admin' | 'teacher' | 'student';

export interface SchoolSettings {
  name: string;
  tagline: string;
  address: string;
  phone: string;
  email: string;
  academicYear: string;
  currencySymbol: string;
  logoUrl: string;
  session: string;
}

export interface ClassItem {
  id: string;
  name: string; // e.g., "Class 6A"
  section: string; // "A", "B"
  grade: string; // "6"
  classTeacherId?: string;
  studentCount?: number;
}

export interface Student {
  id: string;
  name: string;
  rollNo: string;
  classId: string;
  fatherName: string;
  motherName: string;
  phone: string;
  dob: string;
  gender: 'Male' | 'Female' | 'Other';
  address: string;
  bloodGroup: string;
  photoUrl?: string;
  totalFee: number;
  paidFee: number;
  username: string;
  password?: string;
}

export interface TeacherAccess {
  attendance: boolean;
  homework: boolean;
  timetable: boolean;
  exams: boolean;
  studyMaterial: boolean;
  questionPapers: boolean;
  notices: boolean;
  leaves: boolean;
  leaderboard: boolean;
}

export interface Teacher {
  id: string;
  name: string;
  subject: string;
  phone: string;
  email: string;
  qualification: string;
  salary: number;
  assignedClassId?: string;
  photoUrl?: string;
  username: string;
  password?: string;
  access: TeacherAccess;
}

export interface AttendanceRecord {
  id: string;
  date: string; // YYYY-MM-DD
  classId: string;
  studentId: string;
  status: 'Present' | 'Absent' | 'Late';
}

export interface TeacherAttendanceRecord {
  id: string;
  date: string;
  teacherId: string;
  status: 'Present' | 'Absent' | 'Late';
  checkIn?: string;
  checkOut?: string;
}

export interface Homework {
  id: string;
  classId: string;
  subject: string;
  description: string;
  dueDate: string;
  boardPhotoUrl?: string;
  createdByTeacherId?: string;
  createdAt: string;
  status?: 'Pending' | 'Completed';
}

export interface OnlineClass {
  id: string;
  classId: string;
  subject: string;
  topic: string;
  teacherId: string;
  startTime: string;
  endTime: string;
  date: string;
  meetingLink: string;
  platform: 'Zoom' | 'Google Meet' | 'Microsoft Teams' | 'In-App Live';
}

export interface TimetableConfig {
  operatingDays: string[]; // ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
  timeSlots: { id: string; name: string; start: string; end: string }[];
}

export interface TimetableCell {
  id: string;
  classId: string;
  day: string; // "Mon"
  slotId: string;
  subject: string;
  teacherId?: string;
  isBreak?: boolean;
}

export interface ExamSubject {
  id: string;
  examName: string; // e.g. "Mid Term"
  classId: string;
  subject: string;
  maxMarks: number;
  date: string;
}

export interface StudentMark {
  id: string;
  studentId: string;
  examSubjectId: string;
  examName: string;
  marksObtained: number;
}

export interface CurriculumChapter {
  id: string;
  classId: string;
  subject: string;
  chapterNo: number;
  title: string;
  description: string;
  isCompleted: boolean;
}

export interface StudyMaterial {
  id: string;
  classId: string;
  subject: string;
  title: string;
  fileUrl: string;
  fileType: string;
  uploadDate: string;
  uploadedBy: string;
}

export interface QuestionPaper {
  id: string;
  classId: string;
  subject: string;
  examType: string;
  title: string;
  fileUrl?: string;
  isAutoGenerated?: boolean;
  generatedContent?: any;
  uploadDate: string;
}

export interface Question {
  id: string;
  classId: string;
  subject: string;
  chapter: string;
  type: 'MCQ' | 'Short Answer' | 'Long Answer' | 'True/False' | 'Fill in Blank';
  questionText: string;
  marks: number;
  mcqOptions?: string[];
  correctOptionIndex?: number;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  unit: string;
  condition: 'Good' | 'Needs Repair' | 'Replaced';
  lastUpdated: string;
}

export interface FeePayment {
  id: string;
  studentId: string;
  amount: number;
  paymentDate: string;
  note?: string;
  receiptNo: string;
}

export interface Transaction {
  id: string;
  type: 'Income' | 'Expense';
  category: string;
  amount: number;
  description: string;
  date: string;
}

export interface SalaryReceipt {
  id: string;
  teacherId: string;
  month: string; // "October 2026"
  basicSalary: number;
  allowances: number;
  deductions: number;
  netSalary: number;
  paidDate: string;
  receiptNo: string;
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  type: 'General' | 'Urgent' | 'Information';
  audience: 'All' | 'Students' | 'Teachers';
  postedBy: string;
  date: string;
}

export interface LeaveRequest {
  id: string;
  applicantType: 'Teacher' | 'Student';
  applicantId: string;
  applicantName: string;
  classOrSubject?: string;
  leaveType: 'Sick Leave' | 'Casual Leave' | 'Emergency' | 'Other';
  startDate: string;
  endDate: string;
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  appliedDate: string;
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  senderRole: Role;
  receiverId: string;
  content: string;
  timestamp: string;
  isRead: boolean;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  type: 'Exam' | 'Holiday' | 'Event' | 'Sports' | 'Meeting';
  description?: string;
}

export interface Birthday {
  id: string;
  name: string;
  role: 'Student' | 'Teacher';
  classOrSubject: string;
  dob: string;
  photoUrl?: string;
}

export interface SchoolGalleryImage {
  id: string;
  title: string;
  imageUrl: string;
  category: string;
  date: string;
}

export interface VehicleGPS {
  id: string;
  vehicleNo: string;
  driverName: string;
  driverPhone: string;
  routeName: string;
  speedKmH: number;
  currentLocation: string;
  lat: number;
  lng: number;
  status: 'On Route' | 'Stopped' | 'Idle' | 'Offline';
}

export interface TeacherTask {
  id: string;
  teacherId: string;
  title: string;
  dueDate: string;
  status: 'Pending' | 'In Progress' | 'Completed';
  priority: 'High' | 'Medium' | 'Low';
}

export interface Reminder {
  id: string;
  title: string;
  date: string;
  priority: 'High' | 'Medium' | 'Low';
  isCompleted: boolean;
}
